<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\DB;
use Symfony\Component\Process\Process;

/**
 * Produces the SQL file a shared-hosting install imports through phpMyAdmin.
 *
 * The file exists because building 40 tables inside a web request can exceed
 * the 30-second limit some shared hosts enforce, where an import has no such
 * limit. It was previously produced by hand, which meant the deployment guide
 * told people to import a file that no longer matched the migrations — the kind
 * of drift that only surfaces as a mystifying error on somebody's first day.
 *
 * Run against a scratch MySQL/MariaDB database, so the DDL is real MySQL rather
 * than a translation of the SQLite the tests use:
 *
 *     php artisan opes:export-schema --database=opes_schema_build
 */
class ExportInstallSchema extends Command
{
    protected $signature = 'opes:export-schema
        {--database=opes_schema_build : Scratch database to build the schema in}
        {--connection=mysql : The configured connection to build it on}
        {--out=database/schema/opes360-install.sql : Where to write the dump}';

    protected $description = 'Build the schema plus reference data on MySQL and dump it for a phpMyAdmin import';

    public function handle(): int
    {
        $connection = $this->option('connection');
        $database = $this->option('database');
        $out = base_path($this->option('out'));

        Config::set("database.connections.{$connection}.database", null);
        DB::purge($connection);

        $this->line("Rebuilding [{$database}] on [{$connection}]…");
        DB::connection($connection)->statement("DROP DATABASE IF EXISTS `{$database}`");
        DB::connection($connection)->statement("CREATE DATABASE `{$database}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

        Config::set("database.connections.{$connection}.database", $database);
        DB::purge($connection);

        $this->call('migrate', ['--force' => true, '--database' => $connection]);

        /*
         * Roles and permissions only. Registration assigns the owner role by
         * looking it up, so on a database without them every business that
         * signs up gets an account that can do nothing — which is why they
         * belong in the import rather than being left to the installer. No
         * companies, no users, no demo data: that is install.php's job.
         */
        $this->call('db:seed', ['--class' => 'RolePermissionSeeder', '--force' => true, '--database' => $connection]);

        $config = config("database.connections.{$connection}");

        @mkdir(dirname($out), 0755, true);

        $process = new Process([
            $this->dumpBinary(),
            '--host='.$config['host'],
            '--port='.$config['port'],
            '--user='.$config['username'],
            ...($config['password'] !== '' && $config['password'] !== null ? ['--password='.$config['password']] : []),
            // A dump that recreates the database would fight the one cPanel
            // already made for the user, whose name it cannot know.
            '--no-create-db',
            '--skip-add-locks',
            '--skip-comments',
            '--default-character-set=utf8mb4',
            $database,
        ], timeout: 300);

        $process->run();

        if (! $process->isSuccessful()) {
            $this->error('The dump failed: '.trim($process->getErrorOutput()));

            return self::FAILURE;
        }

        file_put_contents($out, $this->header().$process->getOutput());

        DB::connection($connection)->statement("DROP DATABASE IF EXISTS `{$database}`");

        $this->info(sprintf('Wrote %s (%s KB).', $this->option('out'), number_format(filesize($out) / 1024)));

        return self::SUCCESS;
    }

    protected function dumpBinary(): string
    {
        foreach (['mariadb-dump', 'mysqldump'] as $binary) {
            $which = new Process(['which', $binary]);
            $which->run();

            if ($which->isSuccessful()) {
                return trim($which->getOutput());
            }
        }

        return 'mysqldump';
    }

    protected function header(): string
    {
        return implode("\n", [
            '-- '.config('opes.brand.name').' — install schema',
            '--',
            '-- Generated by `php artisan opes:export-schema` from the migrations in',
            '-- database/migrations, so it cannot drift from them. Import into an EMPTY',
            '-- database through phpMyAdmin, then run install.php to create your',
            '-- administrator. Against a database that already holds data the import will',
            '-- fail on the existing tables, which is the intended behaviour.',
            '--',
            '-- Contains: the schema, recorded as already migrated, plus the roles and',
            '-- permissions the application cannot work without. No businesses, no users.',
            '--',
            '-- Generated: '.now()->toDateString(),
            '', '',
        ]);
    }
}
