-- Opes360 — install schema
--
-- Generated by `php artisan opes:export-schema` from the migrations in
-- database/migrations, so it cannot drift from them. Import into an EMPTY
-- database through phpMyAdmin, then run install.php to create your
-- administrator. Against a database that already holds data the import will
-- fail on the existing tables, which is the intended behaviour.
--
-- Contains: the schema, recorded as already migrated, plus the roles and
-- permissions the application cannot work without. No businesses, no users.
--
-- Generated: 2026-08-02

/*M!999999\- enable the sandbox mode */ 

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `activity_log`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `activity_log` (
  `id` char(26) NOT NULL,
  `company_id` char(26) DEFAULT NULL,
  `user_id` bigint(20) unsigned DEFAULT NULL,
  `event` varchar(255) NOT NULL,
  `subject_type` varchar(255) DEFAULT NULL,
  `subject_id` varchar(255) DEFAULT NULL,
  `properties` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`properties`)),
  `ip` varchar(45) DEFAULT NULL,
  `user_agent` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `activity_log_user_id_foreign` (`user_id`),
  KEY `activity_log_company_id_created_at_index` (`company_id`,`created_at`),
  KEY `activity_log_subject_type_subject_id_index` (`subject_type`,`subject_id`),
  CONSTRAINT `activity_log_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE SET NULL,
  CONSTRAINT `activity_log_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `activity_log` DISABLE KEYS */;
/*!40000 ALTER TABLE `activity_log` ENABLE KEYS */;
DROP TABLE IF EXISTS `artisan_testimonials`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `artisan_testimonials` (
  `id` char(26) NOT NULL,
  `company_id` char(26) NOT NULL,
  `artisan_id` char(26) NOT NULL,
  `author_name` varchar(255) NOT NULL,
  `rating` tinyint(3) unsigned DEFAULT NULL,
  `body` text NOT NULL,
  `is_published` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `artisan_testimonials_company_id_foreign` (`company_id`),
  KEY `artisan_testimonials_artisan_id_is_published_index` (`artisan_id`,`is_published`),
  CONSTRAINT `artisan_testimonials_artisan_id_foreign` FOREIGN KEY (`artisan_id`) REFERENCES `artisans` (`id`) ON DELETE CASCADE,
  CONSTRAINT `artisan_testimonials_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `artisan_testimonials` DISABLE KEYS */;
/*!40000 ALTER TABLE `artisan_testimonials` ENABLE KEYS */;
DROP TABLE IF EXISTS `artisans`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `artisans` (
  `id` char(26) NOT NULL,
  `company_id` char(26) NOT NULL,
  `user_id` bigint(20) unsigned DEFAULT NULL,
  `slug` varchar(255) NOT NULL,
  `artisan_number` varchar(255) DEFAULT NULL,
  `full_name` varchar(255) NOT NULL,
  `photo_path` varchar(255) DEFAULT NULL,
  `occupation` varchar(255) DEFAULT NULL,
  `trade_category` varchar(255) DEFAULT NULL,
  `skills` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`skills`)),
  `biography` text DEFAULT NULL,
  `years_experience` smallint(5) unsigned DEFAULT NULL,
  `certifications` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`certifications`)),
  `languages` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`languages`)),
  `coverage_area` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`coverage_area`)),
  `phones` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`phones`)),
  `whatsapp` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `website` varchar(255) DEFAULT NULL,
  `address` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`address`)),
  `latitude` decimal(10,7) DEFAULT NULL,
  `longitude` decimal(10,7) DEFAULT NULL,
  `working_hours` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`working_hours`)),
  `emergency_contact` varchar(255) DEFAULT NULL,
  `socials` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`socials`)),
  `verification_token_id` char(26) DEFAULT NULL,
  `is_verified` tinyint(1) NOT NULL DEFAULT 0,
  `is_published` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `artisans_slug_unique` (`slug`),
  KEY `artisans_user_id_foreign` (`user_id`),
  KEY `artisans_verification_token_id_foreign` (`verification_token_id`),
  KEY `artisans_company_id_trade_category_index` (`company_id`,`trade_category`),
  KEY `artisans_company_id_is_published_index` (`company_id`,`is_published`),
  CONSTRAINT `artisans_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `artisans_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `artisans_verification_token_id_foreign` FOREIGN KEY (`verification_token_id`) REFERENCES `verification_tokens` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `artisans` DISABLE KEYS */;
/*!40000 ALTER TABLE `artisans` ENABLE KEYS */;
DROP TABLE IF EXISTS `business_documents`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `business_documents` (
  `id` char(26) NOT NULL,
  `company_id` char(26) NOT NULL,
  `template` varchar(255) NOT NULL,
  `title` varchar(255) NOT NULL,
  `reference` varchar(255) DEFAULT NULL,
  `recipient` varchar(255) DEFAULT NULL,
  `fields` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`fields`)),
  `body` longtext NOT NULL,
  `status` varchar(255) NOT NULL DEFAULT 'draft',
  `issued_at` timestamp NULL DEFAULT NULL,
  `voided_at` timestamp NULL DEFAULT NULL,
  `voided_by` bigint(20) unsigned DEFAULT NULL,
  `void_reason` varchar(255) DEFAULT NULL,
  `issued_by` bigint(20) unsigned DEFAULT NULL,
  `content_hash` varchar(64) DEFAULT NULL,
  `verification_token_id` char(26) DEFAULT NULL,
  `created_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `business_documents_company_id_reference_unique` (`company_id`,`reference`),
  KEY `business_documents_voided_by_foreign` (`voided_by`),
  KEY `business_documents_issued_by_foreign` (`issued_by`),
  KEY `business_documents_verification_token_id_foreign` (`verification_token_id`),
  KEY `business_documents_created_by_foreign` (`created_by`),
  KEY `business_documents_company_id_status_index` (`company_id`,`status`),
  KEY `business_documents_company_id_template_index` (`company_id`,`template`),
  CONSTRAINT `business_documents_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `business_documents_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `business_documents_issued_by_foreign` FOREIGN KEY (`issued_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `business_documents_verification_token_id_foreign` FOREIGN KEY (`verification_token_id`) REFERENCES `verification_tokens` (`id`) ON DELETE SET NULL,
  CONSTRAINT `business_documents_voided_by_foreign` FOREIGN KEY (`voided_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `business_documents` DISABLE KEYS */;
/*!40000 ALTER TABLE `business_documents` ENABLE KEYS */;
DROP TABLE IF EXISTS `cache`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `cache` (
  `key` varchar(255) NOT NULL,
  `value` mediumtext NOT NULL,
  `expiration` int(11) NOT NULL,
  PRIMARY KEY (`key`),
  KEY `cache_expiration_index` (`expiration`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `cache` DISABLE KEYS */;
/*!40000 ALTER TABLE `cache` ENABLE KEYS */;
DROP TABLE IF EXISTS `cache_locks`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `cache_locks` (
  `key` varchar(255) NOT NULL,
  `owner` varchar(255) NOT NULL,
  `expiration` int(11) NOT NULL,
  PRIMARY KEY (`key`),
  KEY `cache_locks_expiration_index` (`expiration`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `cache_locks` DISABLE KEYS */;
/*!40000 ALTER TABLE `cache_locks` ENABLE KEYS */;
DROP TABLE IF EXISTS `card_issuances`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `card_issuances` (
  `id` char(26) NOT NULL,
  `company_id` char(26) NOT NULL,
  `partner_client_id` char(26) DEFAULT NULL,
  `asset` varchar(255) NOT NULL,
  `design` varchar(255) NOT NULL,
  `subject_name` varchar(255) NOT NULL,
  `fee` int(10) unsigned NOT NULL,
  `currency` varchar(3) NOT NULL DEFAULT 'XAF',
  `status` varchar(255) NOT NULL DEFAULT 'billed',
  `void_reason` text DEFAULT NULL,
  `issued_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `card_issuances_partner_client_id_foreign` (`partner_client_id`),
  KEY `card_issuances_issued_by_foreign` (`issued_by`),
  KEY `card_issuances_company_id_created_at_index` (`company_id`,`created_at`),
  KEY `card_issuances_company_id_status_index` (`company_id`,`status`),
  CONSTRAINT `card_issuances_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `card_issuances_issued_by_foreign` FOREIGN KEY (`issued_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `card_issuances_partner_client_id_foreign` FOREIGN KEY (`partner_client_id`) REFERENCES `partner_clients` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `card_issuances` DISABLE KEYS */;
/*!40000 ALTER TABLE `card_issuances` ENABLE KEYS */;
DROP TABLE IF EXISTS `categories`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `categories` (
  `id` char(26) NOT NULL,
  `company_id` char(26) NOT NULL,
  `parent_id` char(26) DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `sort_order` int(10) unsigned NOT NULL DEFAULT 0,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `categories_company_id_slug_unique` (`company_id`,`slug`),
  KEY `categories_parent_id_foreign` (`parent_id`),
  CONSTRAINT `categories_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `categories_parent_id_foreign` FOREIGN KEY (`parent_id`) REFERENCES `categories` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `categories` DISABLE KEYS */;
/*!40000 ALTER TABLE `categories` ENABLE KEYS */;
DROP TABLE IF EXISTS `companies`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `companies` (
  `id` char(26) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `motto` varchar(255) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `industry` varchar(255) DEFAULT NULL,
  `registration_number` varchar(255) DEFAULT NULL,
  `tax_id` text DEFAULT NULL,
  `tax_id_index` varchar(255) DEFAULT NULL,
  `vat_number` text DEFAULT NULL,
  `tax_regime` varchar(255) DEFAULT NULL,
  `tax_centre` varchar(255) DEFAULT NULL,
  `capital_social` decimal(15,2) DEFAULT NULL,
  `vat_registered` tinyint(1) NOT NULL DEFAULT 0,
  `vat_rate` decimal(7,4) NOT NULL DEFAULT 19.2500,
  `prices_include_tax` tinyint(1) NOT NULL DEFAULT 0,
  `default_sales_account` varchar(255) NOT NULL DEFAULT 'sales_goods',
  `address_line1` varchar(255) DEFAULT NULL,
  `address_line2` varchar(255) DEFAULT NULL,
  `city` varchar(255) DEFAULT NULL,
  `region` varchar(255) DEFAULT NULL,
  `country` varchar(2) DEFAULT NULL,
  `postal_code` varchar(255) DEFAULT NULL,
  `latitude` decimal(10,7) DEFAULT NULL,
  `longitude` decimal(10,7) DEFAULT NULL,
  `website` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `phones` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`phones`)),
  `socials` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`socials`)),
  `operating_hours` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`operating_hours`)),
  `logo_path` varchar(255) DEFAULT NULL,
  `banner_path` varchar(255) DEFAULT NULL,
  `brand_tokens` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`brand_tokens`)),
  `letterhead_design` varchar(255) DEFAULT NULL,
  `card_design` varchar(255) DEFAULT NULL,
  `currency` varchar(3) NOT NULL DEFAULT 'USD',
  `timezone` varchar(255) NOT NULL DEFAULT 'UTC',
  `account_type` varchar(255) NOT NULL DEFAULT 'active',
  `kind` varchar(255) NOT NULL DEFAULT 'business',
  `partner_code` varchar(255) DEFAULT NULL,
  `referred_by_company_id` char(26) DEFAULT NULL,
  `referred_at` timestamp NULL DEFAULT NULL,
  `plan` varchar(255) NOT NULL DEFAULT 'basic',
  `plan_renews_at` timestamp NULL DEFAULT NULL,
  `renewal_reminder_stage` varchar(255) DEFAULT NULL,
  `renewal_reminder_for` date DEFAULT NULL,
  `suspended_at` timestamp NULL DEFAULT NULL,
  `demo_expires_at` timestamp NULL DEFAULT NULL,
  `loyalty_enabled` tinyint(1) NOT NULL DEFAULT 0,
  `loyalty_points_per_amount` decimal(12,2) NOT NULL DEFAULT 100.00,
  `loyalty_point_value` decimal(12,4) NOT NULL DEFAULT 1.0000,
  `status` varchar(255) NOT NULL DEFAULT 'active',
  `owner_id` bigint(20) unsigned NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `companies_slug_unique` (`slug`),
  UNIQUE KEY `companies_partner_code_unique` (`partner_code`),
  KEY `companies_owner_id_foreign` (`owner_id`),
  KEY `companies_status_index` (`status`),
  KEY `companies_tax_id_index_index` (`tax_id_index`),
  KEY `companies_referred_by_company_id_foreign` (`referred_by_company_id`),
  CONSTRAINT `companies_owner_id_foreign` FOREIGN KEY (`owner_id`) REFERENCES `users` (`id`),
  CONSTRAINT `companies_referred_by_company_id_foreign` FOREIGN KEY (`referred_by_company_id`) REFERENCES `companies` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `companies` DISABLE KEYS */;
/*!40000 ALTER TABLE `companies` ENABLE KEYS */;
DROP TABLE IF EXISTS `company_notes`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `company_notes` (
  `id` char(26) NOT NULL,
  `company_id` char(26) NOT NULL,
  `platform_admin_id` bigint(20) unsigned DEFAULT NULL,
  `body` text NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `company_notes_company_id_foreign` (`company_id`),
  KEY `company_notes_platform_admin_id_foreign` (`platform_admin_id`),
  CONSTRAINT `company_notes_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `company_notes_platform_admin_id_foreign` FOREIGN KEY (`platform_admin_id`) REFERENCES `platform_admins` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `company_notes` DISABLE KEYS */;
/*!40000 ALTER TABLE `company_notes` ENABLE KEYS */;
DROP TABLE IF EXISTS `company_reviews`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `company_reviews` (
  `id` char(26) NOT NULL,
  `company_id` char(26) NOT NULL,
  `author_name` varchar(255) NOT NULL,
  `rating` tinyint(3) unsigned NOT NULL,
  `body` text NOT NULL,
  `is_published` tinyint(1) NOT NULL DEFAULT 0,
  `submitted_ip_hash` varchar(64) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `company_reviews_company_id_is_published_index` (`company_id`,`is_published`),
  CONSTRAINT `company_reviews_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `company_reviews` DISABLE KEYS */;
/*!40000 ALTER TABLE `company_reviews` ENABLE KEYS */;
DROP TABLE IF EXISTS `company_user`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `company_user` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `company_id` char(26) NOT NULL,
  `user_id` bigint(20) unsigned NOT NULL,
  `role_id` bigint(20) unsigned NOT NULL,
  `job_title` varchar(255) DEFAULT NULL,
  `status` varchar(255) NOT NULL DEFAULT 'active',
  `invited_at` timestamp NULL DEFAULT NULL,
  `joined_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `company_user_company_id_user_id_unique` (`company_id`,`user_id`),
  KEY `company_user_user_id_foreign` (`user_id`),
  KEY `company_user_role_id_foreign` (`role_id`),
  CONSTRAINT `company_user_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `company_user_role_id_foreign` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`),
  CONSTRAINT `company_user_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `company_user` DISABLE KEYS */;
/*!40000 ALTER TABLE `company_user` ENABLE KEYS */;
DROP TABLE IF EXISTS `company_user_permission`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `company_user_permission` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `company_id` char(26) NOT NULL,
  `user_id` bigint(20) unsigned NOT NULL,
  `permission_id` bigint(20) unsigned NOT NULL,
  `granted` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `cup_unique` (`company_id`,`user_id`,`permission_id`),
  KEY `company_user_permission_user_id_foreign` (`user_id`),
  KEY `company_user_permission_permission_id_foreign` (`permission_id`),
  CONSTRAINT `company_user_permission_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `company_user_permission_permission_id_foreign` FOREIGN KEY (`permission_id`) REFERENCES `permissions` (`id`) ON DELETE CASCADE,
  CONSTRAINT `company_user_permission_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `company_user_permission` DISABLE KEYS */;
/*!40000 ALTER TABLE `company_user_permission` ENABLE KEYS */;
DROP TABLE IF EXISTS `contact_notes`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `contact_notes` (
  `id` char(26) NOT NULL,
  `company_id` char(26) NOT NULL,
  `contact_id` char(26) NOT NULL,
  `user_id` bigint(20) unsigned DEFAULT NULL,
  `type` varchar(255) NOT NULL DEFAULT 'note',
  `body` text NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `contact_notes_company_id_foreign` (`company_id`),
  KEY `contact_notes_user_id_foreign` (`user_id`),
  KEY `contact_notes_contact_id_created_at_index` (`contact_id`,`created_at`),
  CONSTRAINT `contact_notes_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `contact_notes_contact_id_foreign` FOREIGN KEY (`contact_id`) REFERENCES `contacts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `contact_notes_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `contact_notes` DISABLE KEYS */;
/*!40000 ALTER TABLE `contact_notes` ENABLE KEYS */;
DROP TABLE IF EXISTS `contacts`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `contacts` (
  `id` char(26) NOT NULL,
  `company_id` char(26) NOT NULL,
  `type` varchar(255) NOT NULL DEFAULT 'customer',
  `name` varchar(255) NOT NULL,
  `company_name` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `phones` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`phones`)),
  `whatsapp` varchar(255) DEFAULT NULL,
  `address` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`address`)),
  `tax_id` text DEFAULT NULL,
  `tax_id_index` varchar(255) DEFAULT NULL,
  `credit_limit` decimal(15,2) DEFAULT NULL,
  `payment_terms_days` smallint(5) unsigned DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `tags` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`tags`)),
  `balance` decimal(15,2) NOT NULL DEFAULT 0.00,
  `loyalty_points` int(10) unsigned NOT NULL DEFAULT 0,
  `loyalty_card_number` varchar(255) DEFAULT NULL,
  `loyalty_card_issued_at` timestamp NULL DEFAULT NULL,
  `loyalty_verification_token_id` char(26) DEFAULT NULL,
  `avatar_path` varchar(255) DEFAULT NULL,
  `created_by` bigint(20) unsigned DEFAULT NULL,
  `device_id` char(26) DEFAULT NULL,
  `synced_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `sync_sequence` bigint(20) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `contacts_company_id_loyalty_card_number_unique` (`company_id`,`loyalty_card_number`),
  KEY `contacts_created_by_foreign` (`created_by`),
  KEY `contacts_company_id_type_index` (`company_id`,`type`),
  KEY `contacts_company_id_tax_id_index_index` (`company_id`,`tax_id_index`),
  KEY `contacts_company_id_name_index` (`company_id`,`name`),
  KEY `contacts_sync_sequence_index` (`sync_sequence`),
  KEY `contacts_loyalty_verification_token_id_foreign` (`loyalty_verification_token_id`),
  CONSTRAINT `contacts_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `contacts_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `contacts_loyalty_verification_token_id_foreign` FOREIGN KEY (`loyalty_verification_token_id`) REFERENCES `verification_tokens` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `contacts` DISABLE KEYS */;
/*!40000 ALTER TABLE `contacts` ENABLE KEYS */;
DROP TABLE IF EXISTS `devices`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `devices` (
  `id` char(26) NOT NULL,
  `company_id` char(26) NOT NULL,
  `user_id` bigint(20) unsigned NOT NULL,
  `name` varchar(255) NOT NULL,
  `platform` varchar(255) DEFAULT NULL,
  `token_hash` varchar(255) NOT NULL,
  `pending_count` int(10) unsigned NOT NULL DEFAULT 0,
  `last_synced_at` timestamp NULL DEFAULT NULL,
  `revoked_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `devices_token_hash_unique` (`token_hash`),
  KEY `devices_user_id_foreign` (`user_id`),
  KEY `devices_company_id_user_id_index` (`company_id`,`user_id`),
  CONSTRAINT `devices_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `devices_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `devices` DISABLE KEYS */;
/*!40000 ALTER TABLE `devices` ENABLE KEYS */;
DROP TABLE IF EXISTS `document_approvals`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `document_approvals` (
  `id` char(26) NOT NULL,
  `company_id` char(26) NOT NULL,
  `document_id` char(26) NOT NULL,
  `user_id` bigint(20) unsigned DEFAULT NULL,
  `action` varchar(255) NOT NULL,
  `comment` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `document_approvals_company_id_foreign` (`company_id`),
  KEY `document_approvals_user_id_foreign` (`user_id`),
  KEY `document_approvals_document_id_created_at_index` (`document_id`,`created_at`),
  CONSTRAINT `document_approvals_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `document_approvals_document_id_foreign` FOREIGN KEY (`document_id`) REFERENCES `documents` (`id`) ON DELETE CASCADE,
  CONSTRAINT `document_approvals_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `document_approvals` DISABLE KEYS */;
/*!40000 ALTER TABLE `document_approvals` ENABLE KEYS */;
DROP TABLE IF EXISTS `document_lines`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `document_lines` (
  `id` char(26) NOT NULL,
  `company_id` char(26) NOT NULL,
  `document_id` char(26) NOT NULL,
  `item_id` char(26) DEFAULT NULL,
  `description` varchar(255) NOT NULL,
  `quantity` decimal(15,3) NOT NULL DEFAULT 1.000,
  `unit` varchar(255) NOT NULL DEFAULT 'unit',
  `unit_price` decimal(15,2) NOT NULL DEFAULT 0.00,
  `discount_type` varchar(255) DEFAULT NULL,
  `discount_value` decimal(15,2) NOT NULL DEFAULT 0.00,
  `tax_rate_id` char(26) DEFAULT NULL,
  `tax_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `line_total` decimal(15,2) NOT NULL DEFAULT 0.00,
  `sort_order` int(10) unsigned NOT NULL DEFAULT 0,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `document_lines_company_id_foreign` (`company_id`),
  KEY `document_lines_item_id_foreign` (`item_id`),
  KEY `document_lines_tax_rate_id_foreign` (`tax_rate_id`),
  KEY `document_lines_document_id_sort_order_index` (`document_id`,`sort_order`),
  CONSTRAINT `document_lines_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `document_lines_document_id_foreign` FOREIGN KEY (`document_id`) REFERENCES `documents` (`id`) ON DELETE CASCADE,
  CONSTRAINT `document_lines_item_id_foreign` FOREIGN KEY (`item_id`) REFERENCES `items` (`id`) ON DELETE SET NULL,
  CONSTRAINT `document_lines_tax_rate_id_foreign` FOREIGN KEY (`tax_rate_id`) REFERENCES `tax_rates` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `document_lines` DISABLE KEYS */;
/*!40000 ALTER TABLE `document_lines` ENABLE KEYS */;
DROP TABLE IF EXISTS `documents`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `documents` (
  `id` char(26) NOT NULL,
  `company_id` char(26) NOT NULL,
  `type` varchar(255) NOT NULL,
  `number` varchar(255) DEFAULT NULL,
  `number_lease_id` char(26) DEFAULT NULL,
  `contact_id` char(26) DEFAULT NULL,
  `status` varchar(255) NOT NULL DEFAULT 'draft',
  `issue_date` date DEFAULT NULL,
  `due_date` date DEFAULT NULL,
  `valid_until` date DEFAULT NULL,
  `currency` varchar(3) NOT NULL DEFAULT 'USD',
  `exchange_rate` decimal(15,6) NOT NULL DEFAULT 1.000000,
  `subtotal` decimal(15,2) NOT NULL DEFAULT 0.00,
  `discount_total` decimal(15,2) NOT NULL DEFAULT 0.00,
  `tax_total` decimal(15,2) NOT NULL DEFAULT 0.00,
  `total` decimal(15,2) NOT NULL DEFAULT 0.00,
  `amount_paid` decimal(15,2) NOT NULL DEFAULT 0.00,
  `balance` decimal(15,2) NOT NULL DEFAULT 0.00,
  `notes` text DEFAULT NULL,
  `terms` text DEFAULT NULL,
  `reference` varchar(255) DEFAULT NULL,
  `parent_document_id` char(26) DEFAULT NULL,
  `content_hash` varchar(255) DEFAULT NULL,
  `issued_at` timestamp NULL DEFAULT NULL,
  `issued_by` bigint(20) unsigned DEFAULT NULL,
  `signature_path` varchar(255) DEFAULT NULL,
  `verification_token_id` char(26) DEFAULT NULL,
  `pdf_path` varchar(255) DEFAULT NULL,
  `created_by` bigint(20) unsigned DEFAULT NULL,
  `device_id` char(26) DEFAULT NULL,
  `synced_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `sync_sequence` bigint(20) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `documents_company_id_type_number_unique` (`company_id`,`type`,`number`),
  KEY `documents_number_lease_id_foreign` (`number_lease_id`),
  KEY `documents_contact_id_foreign` (`contact_id`),
  KEY `documents_parent_document_id_foreign` (`parent_document_id`),
  KEY `documents_issued_by_foreign` (`issued_by`),
  KEY `documents_verification_token_id_foreign` (`verification_token_id`),
  KEY `documents_created_by_foreign` (`created_by`),
  KEY `documents_company_id_type_status_issue_date_index` (`company_id`,`type`,`status`,`issue_date`),
  KEY `documents_company_id_contact_id_index` (`company_id`,`contact_id`),
  KEY `documents_company_id_issue_date_index` (`company_id`,`issue_date`),
  KEY `documents_sync_sequence_index` (`sync_sequence`),
  CONSTRAINT `documents_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `documents_contact_id_foreign` FOREIGN KEY (`contact_id`) REFERENCES `contacts` (`id`),
  CONSTRAINT `documents_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `documents_issued_by_foreign` FOREIGN KEY (`issued_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `documents_number_lease_id_foreign` FOREIGN KEY (`number_lease_id`) REFERENCES `number_leases` (`id`) ON DELETE SET NULL,
  CONSTRAINT `documents_parent_document_id_foreign` FOREIGN KEY (`parent_document_id`) REFERENCES `documents` (`id`) ON DELETE SET NULL,
  CONSTRAINT `documents_verification_token_id_foreign` FOREIGN KEY (`verification_token_id`) REFERENCES `verification_tokens` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `documents` DISABLE KEYS */;
/*!40000 ALTER TABLE `documents` ENABLE KEYS */;
DROP TABLE IF EXISTS `events`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `events` (
  `id` char(26) NOT NULL,
  `company_id` char(26) NOT NULL,
  `title` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `venue` varchar(255) DEFAULT NULL,
  `starts_at` timestamp NOT NULL,
  `ends_at` timestamp NULL DEFAULT NULL,
  `status` varchar(255) NOT NULL DEFAULT 'draft',
  `share_token` varchar(32) NOT NULL,
  `created_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `events_share_token_unique` (`share_token`),
  KEY `events_created_by_foreign` (`created_by`),
  KEY `events_company_id_status_index` (`company_id`,`status`),
  KEY `events_company_id_starts_at_index` (`company_id`,`starts_at`),
  CONSTRAINT `events_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `events_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `events` DISABLE KEYS */;
/*!40000 ALTER TABLE `events` ENABLE KEYS */;
DROP TABLE IF EXISTS `failed_jobs`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `failed_jobs` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `uuid` varchar(255) NOT NULL,
  `connection` text NOT NULL,
  `queue` text NOT NULL,
  `payload` longtext NOT NULL,
  `exception` longtext NOT NULL,
  `failed_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `failed_jobs_uuid_unique` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `failed_jobs` DISABLE KEYS */;
/*!40000 ALTER TABLE `failed_jobs` ENABLE KEYS */;
DROP TABLE IF EXISTS `form_responses`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `form_responses` (
  `id` char(26) NOT NULL,
  `company_id` char(26) NOT NULL,
  `form_id` char(26) NOT NULL,
  `answers` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`answers`)),
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `form_responses_company_id_foreign` (`company_id`),
  KEY `form_responses_form_id_created_at_index` (`form_id`,`created_at`),
  CONSTRAINT `form_responses_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `form_responses_form_id_foreign` FOREIGN KEY (`form_id`) REFERENCES `forms` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `form_responses` DISABLE KEYS */;
/*!40000 ALTER TABLE `form_responses` ENABLE KEYS */;
DROP TABLE IF EXISTS `forms`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `forms` (
  `id` char(26) NOT NULL,
  `company_id` char(26) NOT NULL,
  `title` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `fields` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`fields`)),
  `status` varchar(255) NOT NULL DEFAULT 'draft',
  `share_token` varchar(32) NOT NULL,
  `created_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `forms_share_token_unique` (`share_token`),
  KEY `forms_created_by_foreign` (`created_by`),
  KEY `forms_company_id_status_index` (`company_id`,`status`),
  CONSTRAINT `forms_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `forms_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `forms` DISABLE KEYS */;
/*!40000 ALTER TABLE `forms` ENABLE KEYS */;
DROP TABLE IF EXISTS `items`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `items` (
  `id` char(26) NOT NULL,
  `company_id` char(26) NOT NULL,
  `type` varchar(255) NOT NULL DEFAULT 'product',
  `category_id` char(26) DEFAULT NULL,
  `sku` varchar(255) DEFAULT NULL,
  `barcode` varchar(255) DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `unit` varchar(255) NOT NULL DEFAULT 'unit',
  `price` decimal(15,2) NOT NULL DEFAULT 0.00,
  `cost` decimal(15,2) DEFAULT NULL,
  `tax_rate_id` char(26) DEFAULT NULL,
  `track_stock` tinyint(1) NOT NULL DEFAULT 0,
  `reorder_level` decimal(15,3) DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `image_path` varchar(255) DEFAULT NULL,
  `created_by` bigint(20) unsigned DEFAULT NULL,
  `device_id` char(26) DEFAULT NULL,
  `synced_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `sync_sequence` bigint(20) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `items_company_id_sku_unique` (`company_id`,`sku`),
  KEY `items_category_id_foreign` (`category_id`),
  KEY `items_tax_rate_id_foreign` (`tax_rate_id`),
  KEY `items_created_by_foreign` (`created_by`),
  KEY `items_company_id_type_is_active_index` (`company_id`,`type`,`is_active`),
  KEY `items_company_id_barcode_index` (`company_id`,`barcode`),
  KEY `items_sync_sequence_index` (`sync_sequence`),
  CONSTRAINT `items_category_id_foreign` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON DELETE SET NULL,
  CONSTRAINT `items_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `items_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `items_tax_rate_id_foreign` FOREIGN KEY (`tax_rate_id`) REFERENCES `tax_rates` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `items` DISABLE KEYS */;
/*!40000 ALTER TABLE `items` ENABLE KEYS */;
DROP TABLE IF EXISTS `job_batches`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `job_batches` (
  `id` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `total_jobs` int(11) NOT NULL,
  `pending_jobs` int(11) NOT NULL,
  `failed_jobs` int(11) NOT NULL,
  `failed_job_ids` longtext NOT NULL,
  `options` mediumtext DEFAULT NULL,
  `cancelled_at` int(11) DEFAULT NULL,
  `created_at` int(11) NOT NULL,
  `finished_at` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `job_batches` DISABLE KEYS */;
/*!40000 ALTER TABLE `job_batches` ENABLE KEYS */;
DROP TABLE IF EXISTS `jobs`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `jobs` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `queue` varchar(255) NOT NULL,
  `payload` longtext NOT NULL,
  `attempts` tinyint(3) unsigned NOT NULL,
  `reserved_at` int(10) unsigned DEFAULT NULL,
  `available_at` int(10) unsigned NOT NULL,
  `created_at` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `jobs_queue_index` (`queue`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `jobs` DISABLE KEYS */;
/*!40000 ALTER TABLE `jobs` ENABLE KEYS */;
DROP TABLE IF EXISTS `journal_entries`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `journal_entries` (
  `id` char(26) NOT NULL,
  `company_id` char(26) NOT NULL,
  `journal` varchar(4) NOT NULL,
  `reference` varchar(255) DEFAULT NULL,
  `narration` text DEFAULT NULL,
  `entry_date` date NOT NULL,
  `source_type` varchar(255) DEFAULT NULL,
  `source_id` char(26) DEFAULT NULL,
  `reverses_entry_id` char(26) DEFAULT NULL,
  `created_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `journal_entries_source_type_source_id_index` (`source_type`,`source_id`),
  KEY `journal_entries_reverses_entry_id_foreign` (`reverses_entry_id`),
  KEY `journal_entries_created_by_foreign` (`created_by`),
  KEY `journal_entries_company_id_entry_date_index` (`company_id`,`entry_date`),
  KEY `journal_entries_company_id_journal_index` (`company_id`,`journal`),
  CONSTRAINT `journal_entries_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `journal_entries_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `journal_entries_reverses_entry_id_foreign` FOREIGN KEY (`reverses_entry_id`) REFERENCES `journal_entries` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `journal_entries` DISABLE KEYS */;
/*!40000 ALTER TABLE `journal_entries` ENABLE KEYS */;
DROP TABLE IF EXISTS `journal_lines`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `journal_lines` (
  `id` char(26) NOT NULL,
  `company_id` char(26) NOT NULL,
  `journal_entry_id` char(26) NOT NULL,
  `ledger_account_id` char(26) NOT NULL,
  `debit` decimal(15,2) NOT NULL DEFAULT 0.00,
  `credit` decimal(15,2) NOT NULL DEFAULT 0.00,
  `narration` varchar(255) DEFAULT NULL,
  `sort_order` smallint(5) unsigned NOT NULL DEFAULT 0,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `journal_lines_ledger_account_id_foreign` (`ledger_account_id`),
  KEY `journal_lines_company_id_ledger_account_id_index` (`company_id`,`ledger_account_id`),
  KEY `journal_lines_journal_entry_id_index` (`journal_entry_id`),
  CONSTRAINT `journal_lines_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `journal_lines_journal_entry_id_foreign` FOREIGN KEY (`journal_entry_id`) REFERENCES `journal_entries` (`id`) ON DELETE CASCADE,
  CONSTRAINT `journal_lines_ledger_account_id_foreign` FOREIGN KEY (`ledger_account_id`) REFERENCES `ledger_accounts` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `journal_lines` DISABLE KEYS */;
/*!40000 ALTER TABLE `journal_lines` ENABLE KEYS */;
DROP TABLE IF EXISTS `ledger_accounts`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `ledger_accounts` (
  `id` char(26) NOT NULL,
  `company_id` char(26) NOT NULL,
  `number` varchar(12) NOT NULL,
  `name` varchar(255) NOT NULL,
  `class` tinyint(3) unsigned NOT NULL,
  `normal_balance` varchar(6) NOT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ledger_accounts_company_id_number_unique` (`company_id`,`number`),
  KEY `ledger_accounts_company_id_class_index` (`company_id`,`class`),
  CONSTRAINT `ledger_accounts_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `ledger_accounts` DISABLE KEYS */;
/*!40000 ALTER TABLE `ledger_accounts` ENABLE KEYS */;
DROP TABLE IF EXISTS `loyalty_transactions`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `loyalty_transactions` (
  `id` char(26) NOT NULL,
  `company_id` char(26) NOT NULL,
  `contact_id` char(26) NOT NULL,
  `type` varchar(255) NOT NULL,
  `points` int(11) NOT NULL,
  `balance_after` int(10) unsigned NOT NULL,
  `reference_type` varchar(255) DEFAULT NULL,
  `reference_id` varchar(255) DEFAULT NULL,
  `note` varchar(255) DEFAULT NULL,
  `created_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `loyalty_transactions_contact_id_foreign` (`contact_id`),
  KEY `loyalty_transactions_created_by_foreign` (`created_by`),
  KEY `loyalty_transactions_company_id_contact_id_index` (`company_id`,`contact_id`),
  KEY `loyalty_transactions_reference_type_reference_id_index` (`reference_type`,`reference_id`),
  CONSTRAINT `loyalty_transactions_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `loyalty_transactions_contact_id_foreign` FOREIGN KEY (`contact_id`) REFERENCES `contacts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `loyalty_transactions_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `loyalty_transactions` DISABLE KEYS */;
/*!40000 ALTER TABLE `loyalty_transactions` ENABLE KEYS */;
DROP TABLE IF EXISTS `media`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `media` (
  `id` char(26) NOT NULL,
  `company_id` char(26) NOT NULL,
  `collection` varchar(255) NOT NULL DEFAULT 'default',
  `disk` varchar(255) NOT NULL DEFAULT 'public',
  `path` varchar(255) NOT NULL,
  `mime` varchar(255) DEFAULT NULL,
  `size` bigint(20) unsigned DEFAULT NULL,
  `width` int(10) unsigned DEFAULT NULL,
  `height` int(10) unsigned DEFAULT NULL,
  `checksum` varchar(255) DEFAULT NULL,
  `attachable_type` varchar(255) DEFAULT NULL,
  `attachable_id` varchar(255) DEFAULT NULL,
  `sort_order` int(10) unsigned NOT NULL DEFAULT 0,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `media_company_id_foreign` (`company_id`),
  KEY `media_attachable_type_attachable_id_index` (`attachable_type`,`attachable_id`),
  CONSTRAINT `media_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `media` DISABLE KEYS */;
/*!40000 ALTER TABLE `media` ENABLE KEYS */;
DROP TABLE IF EXISTS `migrations`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `migrations` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `migration` varchar(255) NOT NULL,
  `batch` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=41 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `migrations` DISABLE KEYS */;
INSERT INTO `migrations` VALUES
(1,'0001_01_01_000000_create_users_table',1),
(2,'0001_01_01_000001_create_cache_table',1),
(3,'0001_01_01_000002_create_jobs_table',1),
(4,'2026_07_27_000001_create_companies_table',1),
(5,'2026_07_27_000002_create_roles_and_permissions_tables',1),
(6,'2026_07_27_000003_add_opes_columns_to_users_table',1),
(7,'2026_07_27_000004_create_platform_tables',1),
(8,'2026_07_27_000005_create_crm_and_catalogue_tables',1),
(9,'2026_07_27_000006_create_sales_tables',1),
(10,'2026_07_27_000007_create_payment_tables',1),
(11,'2026_07_28_000001_create_artisans_table',1),
(12,'2026_07_28_000002_add_two_factor_columns_to_users_table',1),
(13,'2026_07_28_000003_create_sync_receipts_table',1),
(14,'2026_07_28_000004_create_business_documents_table',1),
(15,'2026_07_31_000001_create_forms_tables',1),
(16,'2026_07_31_000002_create_events_tables',1),
(17,'2026_07_31_100001_add_card_design_to_companies',1),
(18,'2026_07_31_100002_add_letterhead_design_to_companies',1),
(19,'2026_07_31_100003_create_company_reviews_table',1),
(20,'2026_07_31_200001_create_notifications_table',1),
(21,'2026_07_31_300001_add_account_lifecycle_to_companies',1),
(22,'2026_08_01_000001_add_loyalty_settings_to_companies',1),
(23,'2026_08_01_000002_add_loyalty_card_to_contacts',1),
(24,'2026_08_01_000003_create_loyalty_transactions_table',1),
(25,'2026_08_02_000001_add_plan_to_companies',1),
(26,'2026_08_02_000002_create_platform_admins_table',1),
(27,'2026_08_03_000001_create_platform_admin_password_reset_tokens_table',1),
(28,'2026_08_03_000002_add_ip_and_user_agent_to_platform_admin_activity',1),
(29,'2026_08_03_000003_add_soft_deletes_to_platform_admins',1),
(30,'2026_08_04_000001_add_two_factor_columns_to_platform_admins_table',1),
(31,'2026_08_04_000002_add_role_to_platform_admins_table',1),
(32,'2026_08_04_000003_create_company_notes_table',1),
(33,'2026_08_05_000001_create_subscription_payments_table',1),
(34,'2026_08_05_000002_add_plan_renews_at_to_companies',1),
(35,'2026_08_06_000001_add_fiscal_identity_to_companies',1),
(36,'2026_08_07_000001_create_ledger_tables',1),
(37,'2026_08_08_000001_add_default_sales_account_to_companies',1),
(38,'2026_08_08_000002_correct_ledger_account_labels',1),
(39,'2026_08_09_000001_add_renewal_reminder_state_to_companies',1),
(40,'2026_08_10_000001_create_partner_programme_tables',1);
/*!40000 ALTER TABLE `migrations` ENABLE KEYS */;
DROP TABLE IF EXISTS `notifications`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `notifications` (
  `id` char(36) NOT NULL,
  `type` varchar(255) NOT NULL,
  `notifiable_type` varchar(255) NOT NULL,
  `notifiable_id` bigint(20) unsigned NOT NULL,
  `data` text NOT NULL,
  `read_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `notifications_notifiable_type_notifiable_id_index` (`notifiable_type`,`notifiable_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `notifications` DISABLE KEYS */;
/*!40000 ALTER TABLE `notifications` ENABLE KEYS */;
DROP TABLE IF EXISTS `number_leases`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `number_leases` (
  `id` char(26) NOT NULL,
  `company_id` char(26) NOT NULL,
  `document_type` varchar(255) NOT NULL,
  `year` smallint(5) unsigned NOT NULL,
  `range_start` bigint(20) unsigned NOT NULL,
  `range_end` bigint(20) unsigned NOT NULL,
  `next_available` bigint(20) unsigned NOT NULL,
  `device_id` char(26) DEFAULT NULL,
  `status` varchar(255) NOT NULL DEFAULT 'active',
  `void_unused_from` bigint(20) unsigned DEFAULT NULL,
  `issued_at` timestamp NOT NULL,
  `expires_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `number_leases_device_id_foreign` (`device_id`),
  KEY `number_leases_company_id_document_type_year_index` (`company_id`,`document_type`,`year`),
  KEY `number_leases_company_id_status_index` (`company_id`,`status`),
  CONSTRAINT `number_leases_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `number_leases_device_id_foreign` FOREIGN KEY (`device_id`) REFERENCES `devices` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `number_leases` DISABLE KEYS */;
/*!40000 ALTER TABLE `number_leases` ENABLE KEYS */;
DROP TABLE IF EXISTS `partner_clients`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `partner_clients` (
  `id` char(26) NOT NULL,
  `company_id` char(26) NOT NULL,
  `name` varchar(255) NOT NULL,
  `contact_name` varchar(255) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `industry` varchar(255) DEFAULT NULL,
  `city` varchar(255) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `invite_token` varchar(255) NOT NULL,
  `converted_company_id` char(26) DEFAULT NULL,
  `converted_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `partner_clients_invite_token_unique` (`invite_token`),
  KEY `partner_clients_converted_company_id_foreign` (`converted_company_id`),
  KEY `partner_clients_company_id_name_index` (`company_id`,`name`),
  CONSTRAINT `partner_clients_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `partner_clients_converted_company_id_foreign` FOREIGN KEY (`converted_company_id`) REFERENCES `companies` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `partner_clients` DISABLE KEYS */;
/*!40000 ALTER TABLE `partner_clients` ENABLE KEYS */;
DROP TABLE IF EXISTS `partner_commissions`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `partner_commissions` (
  `id` char(26) NOT NULL,
  `company_id` char(26) NOT NULL,
  `source_company_id` char(26) NOT NULL,
  `subscription_payment_id` char(26) NOT NULL,
  `amount` int(10) unsigned NOT NULL,
  `rate` decimal(5,4) NOT NULL,
  `base_amount` int(10) unsigned NOT NULL,
  `currency` varchar(3) NOT NULL DEFAULT 'XAF',
  `status` varchar(255) NOT NULL DEFAULT 'earned',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `partner_commissions_subscription_payment_id_unique` (`subscription_payment_id`),
  KEY `partner_commissions_source_company_id_foreign` (`source_company_id`),
  KEY `partner_commissions_company_id_created_at_index` (`company_id`,`created_at`),
  CONSTRAINT `partner_commissions_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `partner_commissions_source_company_id_foreign` FOREIGN KEY (`source_company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `partner_commissions_subscription_payment_id_foreign` FOREIGN KEY (`subscription_payment_id`) REFERENCES `subscription_payments` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `partner_commissions` DISABLE KEYS */;
/*!40000 ALTER TABLE `partner_commissions` ENABLE KEYS */;
DROP TABLE IF EXISTS `partner_payouts`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `partner_payouts` (
  `id` char(26) NOT NULL,
  `company_id` char(26) NOT NULL,
  `amount` int(10) unsigned NOT NULL,
  `currency` varchar(3) NOT NULL DEFAULT 'XAF',
  `status` varchar(255) NOT NULL DEFAULT 'requested',
  `method` varchar(255) DEFAULT NULL,
  `destination` varchar(255) DEFAULT NULL,
  `note` text DEFAULT NULL,
  `requested_by` bigint(20) unsigned DEFAULT NULL,
  `settled_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `partner_payouts_requested_by_foreign` (`requested_by`),
  KEY `partner_payouts_company_id_status_index` (`company_id`,`status`),
  CONSTRAINT `partner_payouts_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `partner_payouts_requested_by_foreign` FOREIGN KEY (`requested_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `partner_payouts` DISABLE KEYS */;
/*!40000 ALTER TABLE `partner_payouts` ENABLE KEYS */;
DROP TABLE IF EXISTS `password_reset_tokens`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `password_reset_tokens` (
  `email` varchar(255) NOT NULL,
  `token` varchar(255) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `password_reset_tokens` DISABLE KEYS */;
/*!40000 ALTER TABLE `password_reset_tokens` ENABLE KEYS */;
DROP TABLE IF EXISTS `payment_allocations`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `payment_allocations` (
  `id` char(26) NOT NULL,
  `company_id` char(26) NOT NULL,
  `payment_id` char(26) NOT NULL,
  `document_id` char(26) NOT NULL,
  `amount` decimal(15,2) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `payment_allocations_payment_id_document_id_unique` (`payment_id`,`document_id`),
  KEY `payment_allocations_company_id_foreign` (`company_id`),
  KEY `payment_allocations_document_id_index` (`document_id`),
  CONSTRAINT `payment_allocations_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `payment_allocations_document_id_foreign` FOREIGN KEY (`document_id`) REFERENCES `documents` (`id`),
  CONSTRAINT `payment_allocations_payment_id_foreign` FOREIGN KEY (`payment_id`) REFERENCES `payments` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `payment_allocations` DISABLE KEYS */;
/*!40000 ALTER TABLE `payment_allocations` ENABLE KEYS */;
DROP TABLE IF EXISTS `payments`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `payments` (
  `id` char(26) NOT NULL,
  `company_id` char(26) NOT NULL,
  `contact_id` char(26) DEFAULT NULL,
  `method` varchar(255) NOT NULL,
  `amount` decimal(15,2) NOT NULL,
  `currency` varchar(3) NOT NULL DEFAULT 'USD',
  `exchange_rate` decimal(15,6) NOT NULL DEFAULT 1.000000,
  `reference` varchar(255) DEFAULT NULL,
  `provider` varchar(255) DEFAULT NULL,
  `provider_reference` varchar(255) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `received_at` timestamp NOT NULL,
  `received_by` bigint(20) unsigned DEFAULT NULL,
  `device_id` char(26) DEFAULT NULL,
  `synced_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `sync_sequence` bigint(20) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `payments_contact_id_foreign` (`contact_id`),
  KEY `payments_received_by_foreign` (`received_by`),
  KEY `payments_company_id_received_at_index` (`company_id`,`received_at`),
  KEY `payments_company_id_method_index` (`company_id`,`method`),
  KEY `payments_sync_sequence_index` (`sync_sequence`),
  CONSTRAINT `payments_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `payments_contact_id_foreign` FOREIGN KEY (`contact_id`) REFERENCES `contacts` (`id`),
  CONSTRAINT `payments_received_by_foreign` FOREIGN KEY (`received_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `payments` DISABLE KEYS */;
/*!40000 ALTER TABLE `payments` ENABLE KEYS */;
DROP TABLE IF EXISTS `permission_role`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `permission_role` (
  `role_id` bigint(20) unsigned NOT NULL,
  `permission_id` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`role_id`,`permission_id`),
  KEY `permission_role_permission_id_foreign` (`permission_id`),
  CONSTRAINT `permission_role_permission_id_foreign` FOREIGN KEY (`permission_id`) REFERENCES `permissions` (`id`) ON DELETE CASCADE,
  CONSTRAINT `permission_role_role_id_foreign` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `permission_role` DISABLE KEYS */;
INSERT INTO `permission_role` VALUES
(1,1),
(1,2),
(1,3),
(1,4),
(1,5),
(1,6),
(1,7),
(1,8),
(1,9),
(1,10),
(1,11),
(1,12),
(1,13),
(1,14),
(1,15),
(1,16),
(1,17),
(1,18),
(1,19),
(1,20),
(1,21),
(1,22),
(1,23),
(1,24),
(1,25),
(1,26),
(1,27),
(1,28),
(1,29),
(1,30),
(1,31),
(1,32),
(1,33),
(1,34),
(1,35),
(1,36),
(1,37),
(1,38),
(1,39),
(1,40),
(1,41),
(1,42),
(1,43),
(1,44),
(1,45),
(1,46),
(1,47),
(1,48),
(1,49),
(1,50),
(1,51),
(1,52),
(1,53),
(1,54),
(1,55),
(1,56),
(1,57),
(1,58),
(1,59),
(2,1),
(2,2),
(2,3),
(2,4),
(2,5),
(2,6),
(2,7),
(2,8),
(2,9),
(2,10),
(2,11),
(2,12),
(2,13),
(2,14),
(2,15),
(2,16),
(2,17),
(2,18),
(2,19),
(2,20),
(2,21),
(2,22),
(2,23),
(2,24),
(2,25),
(2,26),
(2,27),
(2,28),
(2,29),
(2,30),
(2,31),
(2,32),
(2,33),
(2,34),
(2,35),
(2,36),
(2,37),
(2,38),
(2,39),
(2,40),
(2,41),
(2,42),
(2,43),
(2,44),
(2,45),
(2,46),
(2,47),
(2,48),
(2,49),
(2,50),
(2,51),
(2,52),
(2,53),
(2,54),
(2,55),
(2,56),
(2,57),
(2,58),
(2,59),
(3,1),
(3,5),
(3,6),
(3,7),
(3,8),
(3,10),
(3,11),
(3,12),
(3,14),
(3,15),
(3,17),
(3,18),
(3,19),
(3,21),
(3,22),
(3,23),
(3,25),
(3,26),
(3,27),
(3,28),
(3,30),
(3,31),
(3,32),
(3,33),
(3,34),
(3,35),
(3,36),
(3,37),
(3,38),
(3,39),
(3,40),
(3,41),
(3,42),
(3,43),
(3,44),
(3,45),
(3,46),
(3,47),
(3,48),
(3,49),
(3,50),
(3,52),
(3,56),
(3,58),
(4,1),
(4,5),
(4,6),
(4,7),
(4,8),
(4,11),
(4,12),
(4,14),
(4,15),
(4,16),
(4,17),
(4,18),
(4,19),
(4,21),
(4,26),
(4,27),
(4,30),
(4,34),
(4,35),
(4,40),
(4,43),
(4,44),
(4,45),
(4,46),
(4,47),
(4,58),
(5,1),
(5,5),
(5,6),
(5,7),
(5,11),
(5,12),
(5,14),
(5,15),
(5,17),
(5,18),
(5,19),
(5,21),
(5,26),
(5,27),
(5,30),
(5,31),
(5,32),
(5,34),
(5,35),
(5,36),
(5,37),
(5,39),
(5,40),
(5,42),
(5,43),
(5,48),
(5,50),
(6,1),
(6,5),
(6,11),
(6,12),
(6,14),
(6,15),
(6,17),
(6,18),
(6,21),
(6,35),
(6,39),
(6,40),
(6,42),
(7,1),
(7,5),
(7,11),
(7,14),
(7,17),
(7,21),
(7,26),
(7,30),
(7,34),
(7,35),
(7,40),
(7,43);
/*!40000 ALTER TABLE `permission_role` ENABLE KEYS */;
DROP TABLE IF EXISTS `permissions`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `permissions` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `slug` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `group` varchar(255) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `permissions_slug_unique` (`slug`)
) ENGINE=InnoDB AUTO_INCREMENT=60 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `permissions` DISABLE KEYS */;
INSERT INTO `permissions` VALUES
(1,'business.view','View Business','Business','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(2,'business.update','Update Business','Business','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(3,'business.manage-branding','Manage Branding Business','Business','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(4,'business.manage-stationery','Manage Stationery Business','Business','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(5,'sales.view','View Sales','Sales','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(6,'sales.create','Create Sales','Sales','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(7,'sales.update','Update Sales','Sales','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(8,'sales.issue','Issue Sales','Sales','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(9,'sales.void','Void Sales','Sales','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(10,'sales.approve','Approve Sales','Sales','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(11,'receipts.view','View Receipts','Receipts','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(12,'receipts.create','Create Receipts','Receipts','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(13,'receipts.void','Void Receipts','Receipts','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(14,'payments.view','View Payments','Payments','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(15,'payments.record','Record Payments','Payments','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(16,'payments.refund','Refund Payments','Payments','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(17,'customers.view','View Customers','Customers','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(18,'customers.create','Create Customers','Customers','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(19,'customers.update','Update Customers','Customers','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(20,'customers.delete','Delete Customers','Customers','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(21,'products.view','View Products','Products','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(22,'products.create','Create Products','Products','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(23,'products.update','Update Products','Products','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(24,'products.delete','Delete Products','Products','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(25,'products.adjust-stock','Adjust Stock Products','Products','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(26,'papers.view','View Papers','Papers','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(27,'papers.create','Create Papers','Papers','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(28,'papers.issue','Issue Papers','Papers','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(29,'papers.void','Void Papers','Papers','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(30,'forms.view','View Forms','Forms','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(31,'forms.create','Create Forms','Forms','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(32,'forms.update','Update Forms','Forms','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(33,'forms.delete','Delete Forms','Forms','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(34,'forms.responses','Responses Forms','Forms','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(35,'events.view','View Events','Events','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(36,'events.create','Create Events','Events','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(37,'events.update','Update Events','Events','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(38,'events.void','Void Events','Events','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(39,'events.check-in','Check In Events','Events','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(40,'loyalty.view','View Loyalty','Loyalty','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(41,'loyalty.manage','Manage Loyalty','Loyalty','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(42,'loyalty.redeem','Redeem Loyalty','Loyalty','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(43,'reports.view','View Reports','Reports','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(44,'reports.export','Export Reports','Reports','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(45,'accounting.view','View Accounting','Accounting','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(46,'accounting.export','Export Accounting','Accounting','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(47,'accounting.manage','Manage Accounting','Accounting','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(48,'partners.view','View Partners','Partners','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(49,'partners.manage','Manage Partners','Partners','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(50,'partners.issue','Issue Partners','Partners','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(51,'partners.withdraw','Withdraw Partners','Partners','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(52,'users.view','View Users','Users','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(53,'users.invite','Invite Users','Users','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(54,'users.update-role','Update Role Users','Users','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(55,'users.remove','Remove Users','Users','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(56,'devices.view','View Devices','Devices','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(57,'devices.revoke','Revoke Devices','Devices','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(58,'settings.view','View Settings','Settings','2026-08-02 01:04:48','2026-08-02 01:04:48'),
(59,'settings.update','Update Settings','Settings','2026-08-02 01:04:48','2026-08-02 01:04:48');
/*!40000 ALTER TABLE `permissions` ENABLE KEYS */;
DROP TABLE IF EXISTS `platform_admin_activity`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `platform_admin_activity` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `platform_admin_id` bigint(20) unsigned NOT NULL,
  `action` varchar(255) NOT NULL,
  `subject_type` varchar(255) DEFAULT NULL,
  `subject_id` varchar(255) DEFAULT NULL,
  `meta` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`meta`)),
  `ip_address` varchar(45) DEFAULT NULL,
  `user_agent` varchar(512) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `platform_admin_activity_platform_admin_id_foreign` (`platform_admin_id`),
  KEY `platform_admin_activity_subject_type_subject_id_index` (`subject_type`,`subject_id`),
  CONSTRAINT `platform_admin_activity_platform_admin_id_foreign` FOREIGN KEY (`platform_admin_id`) REFERENCES `platform_admins` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `platform_admin_activity` DISABLE KEYS */;
/*!40000 ALTER TABLE `platform_admin_activity` ENABLE KEYS */;
DROP TABLE IF EXISTS `platform_admin_password_reset_tokens`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `platform_admin_password_reset_tokens` (
  `email` varchar(255) NOT NULL,
  `token` varchar(255) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `platform_admin_password_reset_tokens` DISABLE KEYS */;
/*!40000 ALTER TABLE `platform_admin_password_reset_tokens` ENABLE KEYS */;
DROP TABLE IF EXISTS `platform_admins`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `platform_admins` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `role` varchar(255) NOT NULL DEFAULT 'admin',
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `password` varchar(255) NOT NULL,
  `two_factor_secret` text DEFAULT NULL,
  `two_factor_recovery_codes` text DEFAULT NULL,
  `two_factor_confirmed_at` timestamp NULL DEFAULT NULL,
  `remember_token` varchar(100) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `platform_admins_email_unique` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `platform_admins` DISABLE KEYS */;
/*!40000 ALTER TABLE `platform_admins` ENABLE KEYS */;
DROP TABLE IF EXISTS `receipts`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `receipts` (
  `id` char(26) NOT NULL,
  `company_id` char(26) NOT NULL,
  `payment_id` char(26) NOT NULL,
  `contact_id` char(26) DEFAULT NULL,
  `number` varchar(255) NOT NULL,
  `number_lease_id` char(26) DEFAULT NULL,
  `format` varchar(255) NOT NULL DEFAULT 'thermal80',
  `total` decimal(15,2) NOT NULL,
  `currency` varchar(3) NOT NULL DEFAULT 'USD',
  `status` varchar(255) NOT NULL DEFAULT 'issued',
  `content_hash` varchar(255) DEFAULT NULL,
  `signature_path` varchar(255) DEFAULT NULL,
  `verification_token_id` char(26) DEFAULT NULL,
  `pdf_path` varchar(255) DEFAULT NULL,
  `issued_at` timestamp NOT NULL,
  `cashier_id` bigint(20) unsigned DEFAULT NULL,
  `device_id` char(26) DEFAULT NULL,
  `synced_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `receipts_company_id_number_unique` (`company_id`,`number`),
  KEY `receipts_payment_id_foreign` (`payment_id`),
  KEY `receipts_contact_id_foreign` (`contact_id`),
  KEY `receipts_number_lease_id_foreign` (`number_lease_id`),
  KEY `receipts_verification_token_id_foreign` (`verification_token_id`),
  KEY `receipts_cashier_id_foreign` (`cashier_id`),
  KEY `receipts_company_id_issued_at_index` (`company_id`,`issued_at`),
  CONSTRAINT `receipts_cashier_id_foreign` FOREIGN KEY (`cashier_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `receipts_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `receipts_contact_id_foreign` FOREIGN KEY (`contact_id`) REFERENCES `contacts` (`id`),
  CONSTRAINT `receipts_number_lease_id_foreign` FOREIGN KEY (`number_lease_id`) REFERENCES `number_leases` (`id`) ON DELETE SET NULL,
  CONSTRAINT `receipts_payment_id_foreign` FOREIGN KEY (`payment_id`) REFERENCES `payments` (`id`) ON DELETE CASCADE,
  CONSTRAINT `receipts_verification_token_id_foreign` FOREIGN KEY (`verification_token_id`) REFERENCES `verification_tokens` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `receipts` DISABLE KEYS */;
/*!40000 ALTER TABLE `receipts` ENABLE KEYS */;
DROP TABLE IF EXISTS `roles`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `roles` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `slug` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `level` tinyint(3) unsigned NOT NULL,
  `is_system` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `roles_slug_unique` (`slug`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `roles` DISABLE KEYS */;
INSERT INTO `roles` VALUES
(1,'owner','Owner',NULL,1,1,'2026-08-02 01:04:48','2026-08-02 01:04:48'),
(2,'administrator','Administrator',NULL,2,1,'2026-08-02 01:04:48','2026-08-02 01:04:48'),
(3,'manager','Manager',NULL,3,1,'2026-08-02 01:04:49','2026-08-02 01:04:49'),
(4,'accountant','Accountant',NULL,4,1,'2026-08-02 01:04:49','2026-08-02 01:04:49'),
(5,'sales-officer','Sales Officer',NULL,5,1,'2026-08-02 01:04:49','2026-08-02 01:04:49'),
(6,'cashier','Cashier',NULL,6,1,'2026-08-02 01:04:49','2026-08-02 01:04:49'),
(7,'read-only','Read Only',NULL,7,1,'2026-08-02 01:04:49','2026-08-02 01:04:49');
/*!40000 ALTER TABLE `roles` ENABLE KEYS */;
DROP TABLE IF EXISTS `sessions`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `sessions` (
  `id` varchar(255) NOT NULL,
  `user_id` bigint(20) unsigned DEFAULT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `user_agent` text DEFAULT NULL,
  `payload` longtext NOT NULL,
  `last_activity` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `sessions_user_id_index` (`user_id`),
  KEY `sessions_last_activity_index` (`last_activity`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `sessions` DISABLE KEYS */;
/*!40000 ALTER TABLE `sessions` ENABLE KEYS */;
DROP TABLE IF EXISTS `stock_movements`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `stock_movements` (
  `id` char(26) NOT NULL,
  `company_id` char(26) NOT NULL,
  `item_id` char(26) NOT NULL,
  `quantity` decimal(15,3) NOT NULL,
  `reason` varchar(255) NOT NULL,
  `reference_type` varchar(255) DEFAULT NULL,
  `reference_id` varchar(255) DEFAULT NULL,
  `user_id` bigint(20) unsigned DEFAULT NULL,
  `device_id` char(26) DEFAULT NULL,
  `occurred_at` timestamp NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `stock_movements_item_id_foreign` (`item_id`),
  KEY `stock_movements_user_id_foreign` (`user_id`),
  KEY `stock_movements_company_id_item_id_occurred_at_index` (`company_id`,`item_id`,`occurred_at`),
  KEY `stock_movements_reference_type_reference_id_index` (`reference_type`,`reference_id`),
  CONSTRAINT `stock_movements_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `stock_movements_item_id_foreign` FOREIGN KEY (`item_id`) REFERENCES `items` (`id`) ON DELETE CASCADE,
  CONSTRAINT `stock_movements_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `stock_movements` DISABLE KEYS */;
/*!40000 ALTER TABLE `stock_movements` ENABLE KEYS */;
DROP TABLE IF EXISTS `subscription_payments`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `subscription_payments` (
  `id` char(26) NOT NULL,
  `company_id` char(26) NOT NULL,
  `initiated_by` bigint(20) unsigned DEFAULT NULL,
  `plan` varchar(255) NOT NULL,
  `billing_cycle` varchar(255) NOT NULL DEFAULT 'monthly',
  `amount` decimal(15,2) NOT NULL,
  `currency` varchar(3) NOT NULL DEFAULT 'XAF',
  `provider` varchar(255) NOT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `external_id` varchar(255) NOT NULL,
  `provider_reference` varchar(255) DEFAULT NULL,
  `status` varchar(255) NOT NULL DEFAULT 'pending',
  `failure_reason` varchar(255) DEFAULT NULL,
  `payload` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`payload`)),
  `paid_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `subscription_payments_external_id_unique` (`external_id`),
  KEY `subscription_payments_initiated_by_foreign` (`initiated_by`),
  KEY `subscription_payments_company_id_status_index` (`company_id`,`status`),
  KEY `subscription_payments_provider_status_index` (`provider`,`status`),
  CONSTRAINT `subscription_payments_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `subscription_payments_initiated_by_foreign` FOREIGN KEY (`initiated_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `subscription_payments` DISABLE KEYS */;
/*!40000 ALTER TABLE `subscription_payments` ENABLE KEYS */;
DROP TABLE IF EXISTS `sync_receipts`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `sync_receipts` (
  `id` char(26) NOT NULL,
  `company_id` char(26) NOT NULL,
  `user_id` bigint(20) unsigned DEFAULT NULL,
  `device_id` char(26) DEFAULT NULL,
  `entity_type` varchar(255) NOT NULL,
  `entity_id` varchar(255) NOT NULL,
  `operation` varchar(255) NOT NULL,
  `status` varchar(255) NOT NULL,
  `server_version` int(10) unsigned NOT NULL DEFAULT 1,
  `assigned_number` varchar(255) DEFAULT NULL,
  `error` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `sync_receipts_id_unique` (`id`),
  KEY `sync_receipts_user_id_foreign` (`user_id`),
  KEY `sync_receipts_device_id_foreign` (`device_id`),
  KEY `sync_receipts_company_id_created_at_index` (`company_id`,`created_at`),
  KEY `sync_receipts_entity_type_entity_id_index` (`entity_type`,`entity_id`),
  CONSTRAINT `sync_receipts_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sync_receipts_device_id_foreign` FOREIGN KEY (`device_id`) REFERENCES `devices` (`id`) ON DELETE SET NULL,
  CONSTRAINT `sync_receipts_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `sync_receipts` DISABLE KEYS */;
/*!40000 ALTER TABLE `sync_receipts` ENABLE KEYS */;
DROP TABLE IF EXISTS `sync_sequences`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `sync_sequences` (
  `company_id` char(26) NOT NULL,
  `value` bigint(20) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`company_id`),
  CONSTRAINT `sync_sequences_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `sync_sequences` DISABLE KEYS */;
/*!40000 ALTER TABLE `sync_sequences` ENABLE KEYS */;
DROP TABLE IF EXISTS `tax_rates`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `tax_rates` (
  `id` char(26) NOT NULL,
  `company_id` char(26) NOT NULL,
  `name` varchar(255) NOT NULL,
  `rate` decimal(7,4) NOT NULL,
  `is_compound` tinyint(1) NOT NULL DEFAULT 0,
  `is_default` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `tax_rates_company_id_is_default_index` (`company_id`,`is_default`),
  CONSTRAINT `tax_rates_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `tax_rates` DISABLE KEYS */;
/*!40000 ALTER TABLE `tax_rates` ENABLE KEYS */;
DROP TABLE IF EXISTS `ticket_types`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `ticket_types` (
  `id` char(26) NOT NULL,
  `company_id` char(26) NOT NULL,
  `event_id` char(26) NOT NULL,
  `name` varchar(255) NOT NULL,
  `price` decimal(12,2) NOT NULL DEFAULT 0.00,
  `quantity` int(10) unsigned DEFAULT NULL,
  `sold` int(10) unsigned NOT NULL DEFAULT 0,
  `sort` int(10) unsigned NOT NULL DEFAULT 0,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ticket_types_company_id_foreign` (`company_id`),
  KEY `ticket_types_event_id_sort_index` (`event_id`,`sort`),
  CONSTRAINT `ticket_types_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `ticket_types_event_id_foreign` FOREIGN KEY (`event_id`) REFERENCES `events` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `ticket_types` DISABLE KEYS */;
/*!40000 ALTER TABLE `ticket_types` ENABLE KEYS */;
DROP TABLE IF EXISTS `tickets`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `tickets` (
  `id` char(26) NOT NULL,
  `company_id` char(26) NOT NULL,
  `event_id` char(26) NOT NULL,
  `ticket_type_id` char(26) NOT NULL,
  `serial` varchar(255) NOT NULL,
  `buyer_name` varchar(255) NOT NULL,
  `buyer_email` varchar(255) DEFAULT NULL,
  `buyer_phone` varchar(255) DEFAULT NULL,
  `price` decimal(12,2) NOT NULL DEFAULT 0.00,
  `status` varchar(255) NOT NULL DEFAULT 'issued',
  `checked_in_at` timestamp NULL DEFAULT NULL,
  `checked_in_by` bigint(20) unsigned DEFAULT NULL,
  `paid_at` timestamp NULL DEFAULT NULL,
  `verification_token_id` char(26) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `tickets_company_id_serial_unique` (`company_id`,`serial`),
  KEY `tickets_ticket_type_id_foreign` (`ticket_type_id`),
  KEY `tickets_checked_in_by_foreign` (`checked_in_by`),
  KEY `tickets_verification_token_id_foreign` (`verification_token_id`),
  KEY `tickets_event_id_status_index` (`event_id`,`status`),
  CONSTRAINT `tickets_checked_in_by_foreign` FOREIGN KEY (`checked_in_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `tickets_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `tickets_event_id_foreign` FOREIGN KEY (`event_id`) REFERENCES `events` (`id`) ON DELETE CASCADE,
  CONSTRAINT `tickets_ticket_type_id_foreign` FOREIGN KEY (`ticket_type_id`) REFERENCES `ticket_types` (`id`) ON DELETE CASCADE,
  CONSTRAINT `tickets_verification_token_id_foreign` FOREIGN KEY (`verification_token_id`) REFERENCES `verification_tokens` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `tickets` DISABLE KEYS */;
/*!40000 ALTER TABLE `tickets` ENABLE KEYS */;
DROP TABLE IF EXISTS `users`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `users` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `avatar_path` varchar(255) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `current_company_id` char(26) DEFAULT NULL,
  `theme` varchar(255) NOT NULL DEFAULT 'system',
  `locale` varchar(5) NOT NULL DEFAULT 'en',
  `last_seen_at` timestamp NULL DEFAULT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `password` varchar(255) NOT NULL,
  `two_factor_secret` text DEFAULT NULL,
  `two_factor_recovery_codes` text DEFAULT NULL,
  `two_factor_confirmed_at` timestamp NULL DEFAULT NULL,
  `remember_token` varchar(100) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`),
  KEY `users_current_company_id_foreign` (`current_company_id`),
  CONSTRAINT `users_current_company_id_foreign` FOREIGN KEY (`current_company_id`) REFERENCES `companies` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `users` DISABLE KEYS */;
/*!40000 ALTER TABLE `users` ENABLE KEYS */;
DROP TABLE IF EXISTS `verification_scans`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `verification_scans` (
  `id` char(26) NOT NULL,
  `verification_token_id` char(26) NOT NULL,
  `country` varchar(2) DEFAULT NULL,
  `region` varchar(255) DEFAULT NULL,
  `device_class` varchar(255) DEFAULT NULL,
  `referrer` varchar(255) DEFAULT NULL,
  `scanned_at` timestamp NOT NULL,
  PRIMARY KEY (`id`),
  KEY `verification_scans_verification_token_id_scanned_at_index` (`verification_token_id`,`scanned_at`),
  CONSTRAINT `verification_scans_verification_token_id_foreign` FOREIGN KEY (`verification_token_id`) REFERENCES `verification_tokens` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `verification_scans` DISABLE KEYS */;
/*!40000 ALTER TABLE `verification_scans` ENABLE KEYS */;
DROP TABLE IF EXISTS `verification_tokens`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `verification_tokens` (
  `id` char(26) NOT NULL,
  `token` varchar(22) NOT NULL,
  `company_id` char(26) NOT NULL,
  `subject_type` varchar(255) NOT NULL,
  `subject_id` varchar(255) NOT NULL,
  `revoked_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `verification_tokens_token_unique` (`token`),
  KEY `verification_tokens_company_id_foreign` (`company_id`),
  KEY `verification_tokens_subject_type_subject_id_index` (`subject_type`,`subject_id`),
  CONSTRAINT `verification_tokens_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40000 ALTER TABLE `verification_tokens` DISABLE KEYS */;
/*!40000 ALTER TABLE `verification_tokens` ENABLE KEYS */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

